### ISSUE TITLE
Kytos execution as normal user, and PIDfile creation

### ISSUE THREAD

**Issue by erickvermot** [kytos/kytos#381]
Since PR https://github.com/kytos/kytos/pull/360 It has not been possible anymore to run kytos as a normal user after installing it on the system as root.
Issue https://github.com/kytos/kytos/issues/368 was opened about this, and then closed with https://github.com/kytos/kytos/pull/369, but the problem remains and It is not possible to run kytos as a normal user.
Furthermore, if one installs kytos using setup.py, a /var/run/kytos folder is created (with permission 777) so that a pidfile can be written inside it during execution, but the problem is that (on Arch which uses systemd) this folder is removed after reboot. This makes kytosd unable to run even by root, and complains about permission denied to write to the file, simply because the folder does not exists.
@renanrodrigo @diraol @cemsbr @beraldoleal

**Comment by erickvermot** [comment]
https://askubuntu.com/questions/303120/how-folders-created-in-var-run-on-each-reboot talks about /var/run and systemd

**Comment by erickvermot** [comment]
![2017-05-03-170818_1337x559_scrot](https://cloud.githubusercontent.com/assets/10514972/25679276/34851720-3023-11e7-89ac-2a50a0e5d460.png)

**Comment by erickvermot** [comment]
since https://github.com/kytos/kytos/pull/387 it has been possible to run kytosd as normal user after install, but this is no longuer possible after reboot, since /var/run/kytos is removed and a normal user cannot create it anymore.
If one runs it using root, the deamon starts ok, but then a normal user cannot run it because the pid file and folder belongs to root and has permission 755 (probably because of the umask).

simple workaround is to create the folder with permissive permissions: ``sudo mkdir -m 777 /var/run/kytos`` and then you can start kytosd as a normal user.

**Comment by cemsbr** [comment]
This is already solved. Reopen if you still have this problem.

**Comment by erickvermot** [comment]
@cemsbr, I do not understand why you closed this.
Could you show me which action was taken to solve this?
The problem still stands, and I haven't seen any PR related to this since my comment, nor any reason to close it.
@beraldoleal may I reopen this?

**Comment by cemsbr** [comment]
I closed because it was fixed in another issue. Did you erase /var/run/kytos folder before running the latest version?

**Comment by erickvermot** [comment]
oh, which issue? 
Problem still stands for me...
I do not understand your point about erasing /var/run/kytos, since the problem exists around the fact that after reboot /var/run/kytos does not exist anymore, and a regular user cannot create it..
```
user@arch_kytos_usb ~ % kytosd -f   
2017-05-26 10:39:17,647 - INFO [kytos.core.logs] (MainThread) Logging config file "/etc/kytos/logging.ini" loaded successfully.
2017-05-26 10:39:17,647 - INFO [kytos.core.controller] (MainThread) /var/run/kytos
Traceback (most recent call last):
  File "/usr/bin/kytosd", line 4, in <module>
    __import__('pkg_resources').run_script('kytos==2017.1b2.post2', 'kytosd')
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 738, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 1499, in run_script
    exec(code, namespace, namespace)
  File "/usr/lib/python3.6/site-packages/kytos-2017.1b2.post2-py3.6.egg/EGG-INFO/scripts/kytosd", line 61, in <module>
    controller.start()
  File "/usr/lib/python3.6/site-packages/kytos-2017.1b2.post2-py3.6.egg/kytos/core/controller.py", line 122, in start
    self.create_pidfile()
  File "/usr/lib/python3.6/site-packages/kytos-2017.1b2.post2-py3.6.egg/kytos/core/controller.py", line 134, in create_pidfile
    pid_folder.mkdir()
  File "/usr/lib/python3.6/pathlib.py", line 1225, in mkdir
    self._accessor.mkdir(self, mode)
  File "/usr/lib/python3.6/pathlib.py", line 388, in wrapped
    return strfunc(str(pathobj), *args)
PermissionError: [Errno 13] Permission denied: '/var/run/kytos'
1 user@arch_kytos_usb ~ % ls /var/run                                                                                                                                  :(
agetty.reload  dbus             dmeventd-server  initramfs  log  mount           nscd         resolvconf  systemd     udev     user
blkid          dmeventd-client  fsck             lock       lvm  NetworkManager  openvswitch  sudo        tmpfiles.d  udisks2  utmp
user@arch_kytos_usb ~ % ls /var/run/kytos
ls: cannot access '/var/run/kytos': No such file or directory
2 user@arch_kytos_usb ~ % 
```

**Comment by cemsbr** [comment]
Deleting the /var/run/kytos assures it will be recreated with the correct permissions. About it being deleted after restart, we haven't solved it yet and I'm reopening the issue as you suggested.

I believe we should rethink kytos usage by root and unprivileged users.

**Comment by renanrodrigo** [comment]
@macartur when you run kytos as a daemon, the pidfile is created by the Daemon context and this problem doesn't happen. However, we *still* need to create the pidfile in startup if running with `-f`, I think.
Could you please check if there is a way to automatically create the pidfile (as Daemon does) without using the method we use today?
If needed, ask me on IRC so I can explain it better.

**Comment by cemsbr** [comment]
It seems that the daemon receives the pidfile path (currently the same as without the daemon) and creates the file with the same owner as the kytosd process. Thus, I believe we cannot get rid of this problem yet. Is it correct, @macartur?

**Comment by macartur** [comment]
Yes, it is.
